name: E2E - Playwright

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop, 'release/*', 'ci/test-stabilization' ]
  push:
    branches: [ main, 'ci/test-stabilization' ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      E2E_BASE_URL: ${{ vars.E2E_BASE_URL || 'https://sitio-luz.vercel.app' }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (headless)
        run: npm test -- --reporter=html,github

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.ref_name }}-${{ github.run_number }}
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces-${{ github.ref_name }}-${{ github.run_number }}
          path: test-results
          if-no-files-found: ignore


